const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const list=v=>v.split(',').map(x=>x.trim()).filter(Boolean); const number=v=>v?Number(v):null;
function step(name){$$('.tab,.panel').forEach(x=>x.classList.remove('active'));$(`.tab[data-step="${name}"]`).classList.add('active');$(`#${name}`).classList.add('active')}
$$('.tab').forEach(b=>b.onclick=()=>step(b.dataset.step));
async function api(path,options={}){const r=await fetch(path,{headers:{'Content-Type':'application/json'},...options});const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d}
function fillProfile(p){if(!p)return;const f=$('#profile-form');for(const k of ['name','headline','master_resume'])f.elements[k].value=p[k]||'';for(const k of ['target_roles','target_skills','work_modes','dealbreakers'])f.elements[k].value=(p.preferences[k]||[]).join(', ');for(const k of ['location','minimum_salary','target_salary','travel_max_percent'])f.elements[k].value=p.preferences[k]??'';$('#fact-count').textContent=`${p.facts.length} verified facts`}
$('#profile-form').onsubmit=async e=>{e.preventDefault();const f=e.target,m=$('#profile-message');m.textContent='Saving…';try{const x=Object.fromEntries(new FormData(f));const payload={name:x.name,headline:x.headline,master_resume:x.master_resume,preferences:{target_roles:list(x.target_roles),target_skills:list(x.target_skills),work_modes:list(x.work_modes),dealbreakers:list(x.dealbreakers),location:x.location,minimum_salary:number(x.minimum_salary),target_salary:number(x.target_salary),travel_max_percent:number(x.travel_max_percent)}};const d=await api('/api/profile',{method:'POST',body:JSON.stringify(payload)});fillProfile(d.profile);m.textContent='Saved. Master resume preserved.';setTimeout(()=>step('job'),500)}catch(err){m.textContent=err.message}};
$('#job-form').onsubmit=async e=>{e.preventDefault();const m=$('#job-message');m.textContent='Analyzing…';try{const payload=Object.fromEntries(new FormData(e.target));const d=await api('/api/analyze',{method:'POST',body:JSON.stringify(payload)});render(d.analysis);m.textContent='';step('results')}catch(err){m.textContent=err.message}};
function render(a){$('#empty').hidden=true;const b=Object.entries(a.score_breakdown).map(([k,v])=>`<div class="metric"><span>${k}</span><strong>${v}</strong></div>`).join('');const ev=a.evidence.map(x=>`<div class="evidence">${esc(x.fact)}<br><code>${x.fact_id}</code> · ${x.matched_terms.join(', ')}</div>`).join('')||'<p>No direct evidence.</p>';const gaps=a.gaps.map(x=>`<li>${esc(x)}</li>`).join('')||'<li>No material gaps detected.</li>';const dis=a.disqualifiers.map(x=>`<li>${esc(x)}</li>`).join('')||'<li>None detected.</li>';const pay=a.compensation.employer_posted||a.compensation.market_estimate;$('#analysis').hidden=false;$('#analysis').innerHTML=`<div class="hero-result"><div class="score" style="--score:${a.overall_score}"><strong>${a.overall_score}</strong><span>/ 100</span></div><div><span class="recommendation">${a.recommendation}</span><h2>${esc(a.job.title||'Untitled role')}</h2><p>${esc(a.job.company||'Company not supplied')}</p><p>${esc(a.explanation)}</p></div></div><div class="breakdown">${b}</div><div class="columns"><div><div class="card"><h3>Verified evidence</h3>${ev}</div><div class="card"><h3>Matched skills</h3>${a.matched_skills.map(x=>`<span class="tag">${x}</span>`).join('')||'None detected'}</div></div><div><div class="card"><h3>Gaps</h3><ul>${gaps}</ul></div><div class="card"><h3>Disqualifiers</h3><ul class="danger">${dis}</ul></div><div class="card"><h3>Compensation</h3>${pay?`<strong>$${pay.minimum.toLocaleString()}–$${pay.maximum.toLocaleString()}</strong><p>${pay.source.replaceAll('_',' ')} · ${pay.confidence} confidence</p><p>${esc(pay.note)}</p>`:'<p>No posted compensation and no candidate target available. No estimate made.</p>'}</div></div></div><div class="actions"><button id="tailor" class="primary">Generate evidence-bound materials</button></div><div id="material-output"></div>`;$('#tailor').onclick=generate}
async function generate(){const b=$('#tailor');b.disabled=true;b.textContent='Generating…';try{const d=await api('/api/tailor',{method:'POST',body:'{}'}),m=d.materials;$('#material-output').innerHTML=`<div class="columns"><div class="card"><h3>Tailored resume</h3><div class="materials">${esc(m.tailored_resume)}</div></div><div class="card"><h3>Cover letter</h3><div class="materials">${esc(m.cover_letter)}</div></div></div><p>✓ ${m.validation.checked_fact_count} claims checked against verified facts. Master resume unchanged.</p>`}catch(e){alert(e.message)}finally{b.disabled=false;b.textContent='Generate evidence-bound materials'}}
function esc(s){const d=document.createElement('div');d.textContent=s??'';return d.innerHTML}
Promise.all([api('/api/profile'),api('/api/analysis')]).then(([p,a])=>{fillProfile(p.profile);if(a.analysis)render(a.analysis)}).catch(()=>{});
