const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const list=v=>v.split(',').map(x=>x.trim()).filter(Boolean), number=v=>v?Number(v):null;
function step(name){$$('.tab,.panel').forEach(x=>x.classList.remove('active'));$(`.tab[data-step="${name}"]`).classList.add('active');$(`#${name}`).classList.add('active')} $$('.tab').forEach(b=>b.onclick=()=>step(b.dataset.step));
async function api(path,options={}){const r=await fetch(path,{headers:{'Content-Type':'application/json'},...options}),d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d}
function fillProfile(p){if(!p)return;const f=$('#profile-form');for(const k of ['name','headline','master_resume'])f.elements[k].value=p[k]||'';for(const k of ['target_roles','target_skills','work_modes','dealbreakers'])f.elements[k].value=(p.preferences[k]||[]).join(', ');for(const k of ['location','minimum_salary','target_salary','travel_max_percent'])f.elements[k].value=p.preferences[k]??'';$('#fact-count').textContent=`${p.facts.length} verified facts`}
$('#profile-form').onsubmit=async e=>{e.preventDefault();const f=e.target,m=$('#profile-message');m.textContent='Savingâ€¦';try{const x=Object.fromEntries(new FormData(f)),payload={name:x.name,headline:x.headline,master_resume:x.master_resume,preferences:{target_roles:list(x.target_roles),target_skills:list(x.target_skills),work_modes:list(x.work_modes),dealbreakers:list(x.dealbreakers),location:x.location,minimum_salary:number(x.minimum_salary),target_salary:number(x.target_salary),travel_max_percent:number(x.travel_max_percent)}};const d=await api('/api/profile',{method:'POST',body:JSON.stringify(payload)});fillProfile(d.profile);m.textContent='Saved. Master resume preserved.';setTimeout(()=>step('job'),500)}catch(err){m.textContent=err.message}};
$('#job-form').onsubmit=async e=>{e.preventDefault();const m=$('#job-message');m.textContent='Analyzingâ€¦';try{const d=await api('/api/analyze',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});render(d.analysis);m.textContent='';step('results')}catch(err){m.textContent=err.message}};
function render(a){$('#empty').hidden=true;const b=Object.entries(a.score_breakdown).map(([k,v])=>`<div class="metric"><span>${k}</span><strong>${v}</strong></div>`).join(''),ev=a.evidence.map(x=>`<div class="evidence">${esc(x.fact)}<br><code>${x.fact_id}</code> Â· ${x.matched_terms.join(', ')}</div>`).join('')||'<p>No direct evidence.</p>';$('#analysis').hidden=false;$('#analysis').innerHTML=`<div class="hero-result"><div class="score" style="--score:${a.overall_score}"><strong>${a.overall_score}</strong><span>/ 100</span></div><div><span class="recommendation">${a.recommendation}</span><h2>${esc(a.job.title||'Untitled role')}</h2><p>${esc(a.job.company||'Company not supplied')}</p><p>${esc(a.explanation)}</p></div></div><div class="breakdown">${b}</div><div class="columns"><div class="card"><h3>Verified evidence</h3>${ev}</div><div><div class="card"><h3>Gaps</h3><ul>${a.gaps.map(x=>`<li>${esc(x)}</li>`).join('')||'<li>No material gaps detected.</li>'}</ul></div><div class="card"><h3>Disqualifiers</h3><ul class="danger">${a.disqualifiers.map(x=>`<li>${esc(x)}</li>`).join('')||'<li>None detected.</li>'}</ul></div></div></div><div class="actions"><button id="tailor" class="primary">Build professional resume</button></div><div id="material-output"></div>`;$('#tailor').onclick=generate}
function resumeHtml(r){const facts=[...r.employment,...r.experience];return `<article class="resume-paper"><div class="resume-head"><h1>${esc(r.name)}</h1><p>${esc(r.headline)}</p></div><h4>Executive Profile</h4><p>${esc(r.summary)}</p>${r.competencies.length?`<h4>Core Competencies</h4><p class="skills">${r.competencies.map(esc).join(' â€¢ ')}</p>`:''}<h4>Professional Experience</h4><ul>${facts.map(x=>`<li>${esc(x.text)}</li>`).join('')}</ul>${r.credentials.length?`<h4>Education & Credentials</h4>${r.credentials.map(x=>`<p>${esc(x.text)}</p>`).join('')}`:''}</article>`}
async function generate(){const b=$('#tailor');b.disabled=true;b.textContent='Buildingâ€¦';try{const {materials:m}=await api('/api/tailor',{method:'POST',body:'{}'});$('#material-output').innerHTML=`<div class="resume-toolbar"><div><span class="eyebrow">TAILORED RESUME</span><h2>Review exactly what was produced</h2><p>Changes and source validation stay separate from the resume itself.</p></div><a class="download" href="/api/resume.pdf">Download professional PDF</a></div><div class="review-tabs"><button class="review-tab active" data-view="resume-view">Complete resume</button><button class="review-tab" data-view="changes-view">What changed <span>${m.change_log.length}</span></button><button class="review-tab" data-view="integrity-view">Integrity check âœ“</button></div><div id="resume-view" class="review-view active">${resumeHtml(m.resume)}</div><div id="changes-view" class="review-view"><div class="review-card"><h2>Sharper positioning, same career truth.</h2>${m.change_log.map((x,i)=>`<div class="change"><strong>${String(i+1).padStart(2,'0')}</strong><div><h3>${esc(x.title)}</h3><p>${esc(x.detail)}</p></div></div>`).join('')}</div></div><div id="integrity-view" class="review-view"><div class="review-card integrity"><div class="verified-seal">âœ“</div><h2>${m.validation.checked_fact_count} claims traced to verified evidence</h2><p>No unsupported skills, achievements, dates, employers, certifications, or experience were introduced.</p><div class="integrity-grid"><div><strong>${m.claim_ledger.length}/${m.claim_ledger.length}</strong><span>Claims verified</span></div><div><strong>0</strong><span>Unsupported claims</span></div><div><strong>Locked</strong><span>Master resume</span></div></div></div></div>`;$$('.review-tab').forEach(x=>x.onclick=()=>{$$('.review-tab,.review-view').forEach(y=>y.classList.remove('active'));x.classList.add('active');$(`#${x.dataset.view}`).classList.add('active')});}catch(e){alert(e.message)}finally{b.disabled=false;b.textContent='Build professional resume'}}
function esc(s){const d=document.createElement('div');d.textContent=s??'';return d.innerHTML} Promise.all([api('/api/profile'),api('/api/analysis')]).then(([p,a])=>{fillProfile(p.profile);if(a.analysis)render(a.analysis)}).catch(()=>{});

